package org.ukrida.hmifukridamobile.ui.theme

import androidx.compose.ui.graphics.Color

// Light scheme
val md_light_primary = Color(0xFF143353)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFF2D4A6B)
val md_light_onPrimaryContainer = Color(0xFF9DBAE0)
val md_light_secondary = Color(0xFF5D5F60)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFDFDFE1)
val md_light_onSecondaryContainer = Color(0xFF616364)
val md_light_tertiary = Color(0xFF003B0B)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_tertiaryContainer = Color(0xFF005514)
val md_light_onTertiaryContainer = Color(0xFF69CD6A)
val md_light_error = Color(0xFFBA1A1A)
val md_light_onError = Color(0xFFFFFFFF)
val md_light_errorContainer = Color(0xFFFFDAD6)
val md_light_onErrorContainer = Color(0xFF93000A)
val md_light_background = Color(0xFFF8F9FF)
val md_light_onBackground = Color(0xFF0B1C30)
val md_light_surface = Color(0xFFFFFFFF)
val md_light_onSurface = Color(0xFF0B1C30)
val md_light_surfaceVariant = Color(0xFFD3E4FE)
val md_light_onSurfaceVariant = Color(0xFF43474E)
val md_light_outline = Color(0xFF73777E)
val md_light_outlineVariant = Color(0xFFC3C6CE)
val md_light_inverseSurface = Color(0xFF213145)
val md_light_inverseOnSurface = Color(0xFFEAF1FF)
val md_light_inversePrimary = Color(0xFFACC9F0)

// Dark scheme (derived from the design system's fixed/inverse tokens)
val md_dark_primary = Color(0xFFACC9F0)
val md_dark_onPrimary = Color(0xFF001C37)
val md_dark_primaryContainer = Color(0xFF2B4869)
val md_dark_onPrimaryContainer = Color(0xFFD2E4FF)
val md_dark_secondary = Color(0xFFC6C6C7)
val md_dark_onSecondary = Color(0xFF1A1C1D)
val md_dark_secondaryContainer = Color(0xFF454748)
val md_dark_onSecondaryContainer = Color(0xFFE2E2E3)
val md_dark_tertiary = Color(0xFF78DC77)
val md_dark_onTertiary = Color(0xFF002204)
val md_dark_tertiaryContainer = Color(0xFF005313)
val md_dark_onTertiaryContainer = Color(0xFF94F990)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_onError = Color(0xFF690005)
val md_dark_errorContainer = Color(0xFF93000A)
val md_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_dark_background = Color(0xFF0B1520)
val md_dark_onBackground = Color(0xFFD3E4FE)
val md_dark_surface = Color(0xFF121D2C)
val md_dark_onSurface = Color(0xFFEAF1FF)
val md_dark_surfaceVariant = Color(0xFF213145)
val md_dark_onSurfaceVariant = Color(0xFFC3C6CE)
val md_dark_outline = Color(0xFF8D9199)
val md_dark_outlineVariant = Color(0xFF43474E)
val md_dark_inverseSurface = Color(0xFFD3E4FE)
val md_dark_inverseOnSurface = Color(0xFF0B1C30)
val md_dark_inversePrimary = Color(0xFF143353)
